FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /src
COPY ["User_Service/User_Service.csproj", "./User_Service/"]
COPY ["Persistence_Layer_Common/Persistence_Layer_Common.csproj", "./Persistence_Layer_Common/"]

RUN dotnet restore "Persistence_Layer_Common/Persistence_Layer_Common.csproj"
RUN dotnet restore "User_Service/User_Service.csproj"

COPY . .
WORKDIR "/src/Persistence_Layer_Common"
RUN dotnet build "Persistence_Layer_Common.csproj" -c Release -o /app/build

WORKDIR "/src/User_Service"
RUN dotnet build "User_Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "User_Service.dll"]








# FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build-env
# WORKDIR /app

# COPY *.csproj ./
# RUN dotnet restore

# COPY . ./
# RUN dotnet publish -c Release -o out

# FROM mcr.microsoft.com/dotnet/aspnet:3.1
# WORKDIR /app
# EXPOSE 5010/tcp
# ENV ASPNETCORE_URLS http://*:5010

# COPY --from=build-env /app/out .

# ENTRYPOINT [“dotnet”, “ProductsAPIServices.dll”]

