// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Persistence_Layer_Common.DB;

namespace DockerDBMigrator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Persistence_Layer_Common.Models.Invesment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<int>("InvestorId")
                        .HasColumnType("integer");

                    b.Property<int>("OppertunityId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId");

                    b.HasIndex("OppertunityId", "InvestorId")
                        .IsUnique();

                    b.ToTable("invesments");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.InvesmentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<double>("Amount")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("InvestorWalletId")
                        .HasColumnType("integer");

                    b.Property<int>("OpportunityWalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvestorWalletId");

                    b.HasIndex("OpportunityWalletId");

                    b.ToTable("InvesmentsTransactions");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.InvestorWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("InvestorId")
                        .HasColumnType("integer");

                    b.Property<double>("money")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("InvestorId")
                        .IsUnique();

                    b.ToTable("InvestorsWallets");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.Opportunity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("opportunities");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.OpportunityWallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("OpportunityId")
                        .HasColumnType("integer");

                    b.Property<double>("money")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("OpportunityId")
                        .IsUnique();

                    b.ToTable("opportunitiesWallets");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Fullname")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasDiscriminator<string>("Discriminator").HasValue("User");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.Investor", b =>
                {
                    b.HasBaseType("Persistence_Layer_Common.Models.User");

                    b.HasDiscriminator().HasValue("Investor");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.Invesment", b =>
                {
                    b.HasOne("Persistence_Layer_Common.Models.Investor", null)
                        .WithMany()
                        .HasForeignKey("InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence_Layer_Common.Models.Opportunity", null)
                        .WithMany()
                        .HasForeignKey("OppertunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.InvesmentTransaction", b =>
                {
                    b.HasOne("Persistence_Layer_Common.Models.InvestorWallet", "InvestorWallet")
                        .WithMany("OutgoingInvesmentTransactions")
                        .HasForeignKey("InvestorWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Persistence_Layer_Common.Models.OpportunityWallet", "OpportunityWallet")
                        .WithMany("IncomingInvesmentTransactions")
                        .HasForeignKey("OpportunityWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvestorWallet");

                    b.Navigation("OpportunityWallet");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.InvestorWallet", b =>
                {
                    b.HasOne("Persistence_Layer_Common.Models.Investor", "Investor")
                        .WithOne("Wallet")
                        .HasForeignKey("Persistence_Layer_Common.Models.InvestorWallet", "InvestorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Investor");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.OpportunityWallet", b =>
                {
                    b.HasOne("Persistence_Layer_Common.Models.Opportunity", "Opportunity")
                        .WithOne("Wallet")
                        .HasForeignKey("Persistence_Layer_Common.Models.OpportunityWallet", "OpportunityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opportunity");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.InvestorWallet", b =>
                {
                    b.Navigation("OutgoingInvesmentTransactions");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.Opportunity", b =>
                {
                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.OpportunityWallet", b =>
                {
                    b.Navigation("IncomingInvesmentTransactions");
                });

            modelBuilder.Entity("Persistence_Layer_Common.Models.Investor", b =>
                {
                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
