FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["User_Service.csproj", "./"]

RUN dotnet restore "./User_Service.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "User_Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "User_Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "UserService.dll"]








# FROM mcr.microsoft.com/dotnet/sdk:3.1 AS build-env
# WORKDIR /app

# COPY *.csproj ./
# RUN dotnet restore

# COPY . ./
# RUN dotnet publish -c Release -o out

# FROM mcr.microsoft.com/dotnet/aspnet:3.1
# WORKDIR /app
# EXPOSE 5010/tcp
# ENV ASPNETCORE_URLS http://*:5010

# COPY --from=build-env /app/out .

# ENTRYPOINT [“dotnet”, “ProductsAPIServices.dll”]

